name: Wait for the commit status
description: Checks GitHub API for a given commit with the status containing the provided context.

branding:
  icon: clock
  color: gray-dark

inputs:
  sha:
    required: true
    type: string
  context:
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Wait for commit status with ${{ inputs.context }}
      shell: bash
      run: |
        go run ${{ github.action_path }}/main.go \
          -sha ${{ inputs.sha }} \
          -context ${{ inputs.context }} \
          -repository ${{ env.GITHUB_REPOSITORY }} \
          -token ${{ env.GITHUB_TOKEN }}
